defaults:
  - 
    scope:
      path: ""
    values:
      layout: "main"
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true



