collections:
  mywikis:
    output: true

defaults:
  - scope:
      path: ""
      type: "mywikis"
    values:
      layout: "wikipage"

wiki_name: Bbangso-wiki
profile_img: https://avatars.githubusercontent.com/u/57941880?v=4
username: Your name
user_role: sample developer
user_description: sample message
instagram_url: https://www.instagram.com/sample
github_url: https://github.com/typegithubid
linkedin_url: 

