collections:
  mywikis:
    output: true

defaults:
  - scope:
      path: ""
      type: "mywikis"
    values:
      layout: "wikipage"

wiki_name: Bbangso-wiki
profile_img: /assets/img/sample-profile.png
username: Your name
user_role: sample developer
user_description: sample message
instagram_url: https://www.instagram.com/sample
github_url: https://github.com/typegithubid
email_address: 
linkedin_url: 

