collections:
  mywikis:
    output: true

defaults:
  - scope:
      path: ""
      type: "mywikis"
    values:
      layout: "wikipage"

wiki_name: Bbangso-wiki
username: bbangso
user_role: frontend developer
